FYP/Controllers/MonitoringController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MySql.Data.MySqlClient;
using Newtonsoft.Json;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Wordprocessing;


namespace FYP.Controllers;

public class MonitoringController : Controller
{
    public string SQLName = "";

    [AllowAnonymous]
    public IActionResult About()
    {
        return View();
    }
    [Authorize(Roles = "admin, farmer")]
    public IActionResult Dashboard()
    {
        return View();
    }

    [Authorize(Roles = "admin, farmer")]
    public IActionResult TempChart()
    {
        List<DataPoint> TData = new List<DataPoint>();

        // Read data into list
        List<TempHumid> Temp = LoadData(1);

        for (int i = Temp.Count - 30; i < Temp.Count; i++)
        {
            TData.Add(new DataPoint(Temp[i].DataInsert.ToString(), Temp[i].Temperature));
        }

        ViewBag.DataPoints1 = JsonConvert.SerializeObject(TData);

        //Second query to get Threshold from Sysuser
        List<Threshold> UserTH = DBUtl.GetList<Threshold>("SELECT * FROM SysUser where FullName = '" + User.Identity!.Name + "'");
        string name = "" + User.Identity!.Name;

        int count = Temp.Count;
        if (Temp[count - 1].Temperature > UserTH[0].ATT || Temp[count - 1].Temperature < UserTH[0].BTT)
        {

            TempData["Message"] = "Threshold Exceeded/Subceed. Temperature Threshold: " + UserTH[0].BTT + "-" + UserTH[0].ATT + "°C. Current Temperature: " + Temp[count - 1].Temperature + "°C";
            TempData["MsgType"] = "danger";

            sendEmail(name, 0);
        }
        else
        {
            TempData["Message"] = "Within Threshold. Temperature Threshold: " + UserTH[0].BTT + "-" + UserTH[0].ATT + "°C.";
            TempData["MsgType"] = "success";
        }

        // Pass data to view
        return View();
    }

    [Authorize(Roles = "admin, farmer")]
    public IActionResult HumidChart()
    {
        List<DataPoint> HData = new List<DataPoint>();

        // Read data into list
        List<TempHumid> Humid = LoadData(1);

        for (int i = Humid.Count - 30; i < Humid.Count; i++)
        {
            HData.Add(new DataPoint(Humid[i].DataInsert.ToString(), Humid[i].Humidity));
        }

        ViewBag.DataPoints2 = JsonConvert.SerializeObject(HData);

        List<Threshold> UserTH = DBUtl.GetList<Threshold>("SELECT * FROM SysUser where FullName = '" + User.Identity!.Name + "'");
        string name = "" + User.Identity!.Name;
        int count = Humid.Count;

        if (Humid[count - 1].Humidity > UserTH[0].AHT || Humid[count - 1].Humidity < UserTH[0].BHT)
        {
            TempData["Message"] = "Threshold Exceeded/Subceed. Humidity Threshold: " + UserTH[0].BHT + "-" + UserTH[0].AHT + "%. Current Humidity: " + Humid[count - 1].Humidity + "%";
            TempData["MsgType"] = "danger";

            sendEmail(name, 1);
        }
        else
        {
            TempData["Message"] = "Within Threshold. Humidity Threshold: " + UserTH[0].BHT + "-" + UserTH[0].AHT + "%";
            TempData["MsgType"] = "success";
        }

        // Pass data to view
        return View();
    }

    [Authorize(Roles = "admin, farmer")]
    public IActionResult CO2Chart()
    {
        List<DataPoint> CData = new List<DataPoint>();

        List<TempHumid> CO2 = LoadData(2);

        for (int i = CO2.Count - 30; i < CO2.Count; i++)
        {
            CData.Add(new DataPoint(CO2[i].DataInsert.ToString(), CO2[i].CO2));
        }

        ViewBag.DataPoints3 = JsonConvert.SerializeObject(CData);

        string name = "" + User.Identity!.Name;
        //Second query to get Threshold from Sysuser
        List<Threshold> UserTH = DBUtl.GetList<Threshold>("SELECT * FROM SysUser where FullName = '" + User.Identity!.Name + "'");
        int count = CO2.Count;
        if (CO2[count - 1].CO2 > UserTH[0].ACOT || CO2[count - 1].CO2 < UserTH[0].BCOT)
        {
            TempData["Message"] = "Threshold Exceeded/Subceed. CO2 Levels Threshold: " + UserTH[0].BCOT + "ppm - " + UserTH[0].ACOT + "ppm. Current CO2 Levels: " + CO2[count - 1].CO2 + "ppm";
            TempData["MsgType"] = "danger";
            sendEmail(name, 2);
        }
        else
        {
            TempData["Message"] = "Within Threshold. Current Threshold: " + UserTH[0].BCOT + "ppm - " + UserTH[0].ACOT + "ppm. Current CO2 Levels: " + CO2[count - 1].CO2 + "ppm";
            TempData["MsgType"] = "success";
        }

        // Pass data to view
        return View();
    }

    public IActionResult HistoricalData()
    {
        return View();
    }

    public IActionResult HistoricalDataPost()
    {
        IFormCollection form = HttpContext.Request.Form;
        string topic = form["Topic"].ToString();
        string year = form["Year"].ToString();

        List<DataPoint> Data = new List<DataPoint>();

        if (topic.Equals("1"))
        {
            List<TempHumid> THCData = LoadData(1);
            if (year.Equals("1"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2023)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].Temperature));
                    }
                }
            }
            else if (year.Equals("2"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2022)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].Temperature));
                    }
                }
            }
            else if (year.Equals("3"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2021)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].Temperature));
                    }
                }
            }
        }
        else if (topic.Equals("2"))
        {
            List<TempHumid> THCData = LoadData(1);
            if (year.Equals("1"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2023)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].Humidity));
                    }
                }
            }
            else if (year.Equals("2"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2022)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].Humidity));
                    }
                }
            }
            else if (year.Equals("3"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2021)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].Humidity));
                    }
                }
            }
        }
        else if (topic.Equals("3"))
        {
            List<TempHumid> THCData = LoadData(2);
            if (year.Equals("1"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2023)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].CO2));
                    }
                }
            }
            else if (year.Equals("2"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2022)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].CO2));
                    }
                }
            }
            else if (year.Equals("3"))
            {
                for (int i = 0; i < THCData.Count; i++)
                {
                    if (THCData[i].DataInsert.Year == 2021)
                    {
                        Data.Add(new DataPoint(THCData[i].DataInsert.ToString(), THCData[i].CO2));
                    }
                }
            }
        }

        ViewBag.DataPoints4 = JsonConvert.SerializeObject(Data);

        return View("HistoricalData");
    }
    private static List<TempHumid> LoadData(int chart)
    {
        if (chart == 1)
        {
            MySqlConnection conn = new MySqlConnection("server=localhost;uid=root;pwd=;database=esp32");
            MySqlCommand query = new MySqlCommand("SELECT * FROM dht22", conn);

            conn.Open();
            MySqlDataReader execute = query.ExecuteReader();

            // Read data into list
            List<TempHumid> THData = new List<TempHumid>();

            while (execute.Read())
            {
                THData.Add(new TempHumid()
                {
                    Temperature = execute.GetInt32("temperature"),
                    Humidity = execute.GetInt32("humidity"),
                    DataInsert = execute.GetDateTime("datetime"),
                });
            }
            conn.Close();
            return (THData);
        }
        else
        {
            MySqlConnection conn = new MySqlConnection("server=localhost;uid=root;pwd=;database=esp32");
            MySqlCommand query = new MySqlCommand("SELECT * FROM co2", conn);

            conn.Open();
            MySqlDataReader execute = query.ExecuteReader();

            // Read data into list
            List<TempHumid> CData = new List<TempHumid>();

            while (execute.Read())
            {
                CData.Add(new TempHumid()
                {

FYP/Views/Shared/Admin.cshtml
<style>
    .font-color {
        color: white;
    }
</style>

<div class="container border-bottom">
    <nav class="navbar navbar-expand-md">
        <div class="container-fluid">

            <img src="~/images/enviro-logo-white.png" height="20" width="90">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex justify-content-between w-100">
                    <div>
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Account" asp-action="Profile">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Account" asp-action="UserList">Users</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle font-color" role="button"
                                   href="#" id="navbarDropdown" data-bs-toggle="dropdown">
                                    Visualisations
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item bi bi-list " asp-controller="Monitoring" asp-action="TempChart"> TempChart</a></li>
                                    <li><a class="dropdown-item bi bi-list " asp-controller="Monitoring" asp-action="HumidChart"> HumidChart</a></li>
                                    <li><a class="dropdown-item bi bi-list " asp-controller="Monitoring" asp-action="CO2Chart"> CO2Chart</a></li>
                                    <li><a class="dropdown-item bi bi-list " asp-controller="Monitoring" asp-action="Dashboard"> OnlineDashboard</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Monitoring" asp-action="HistoricalData">HistoricalData</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Monitoring" asp-action="About">About</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <ul class="nav navbar-nav">
                            <li span class="nav-item">
                                <div class="nav-link font-color">
                                    Welcome @User.Identity!.Name
                                    <a class="bi-box-arrow-right text-decoration-none font-color" asp-controller="Account"
                                       asp-action="Logoff" data-toggle="tooltip" title="Log out"></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

FYP/Views/Shared/Farmer.cshtml
<style>
    .font-color {
        color: white;
    }
</style>

<div class="container border-bottom">
    <nav class="navbar navbar-expand-md">
        <div class="container-fluid">

            <img src="~/images/enviro-logo-white.png" height="20" width="90">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex justify-content-between w-100">
                    <div>
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Account" asp-action="Profile">Profile</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle font-color" role="button"
                                   href="#" id="navbarDropdown" data-bs-toggle="dropdown">
                                    Visualisations
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item bi bi-list" asp-controller="Monitoring" asp-action="TempChart"> TempChart</a></li>
                                    <li><a class="dropdown-item bi bi-list" asp-controller="Monitoring" asp-action="HumidChart"> HumidChart</a></li>
                                    <li><a class="dropdown-item bi bi-list" asp-controller="Monitoring" asp-action="CO2Chart"> CO2Chart</a></li>
                                    <li><a class="dropdown-item bi bi-list" asp-controller="Monitoring" asp-action="Dashboard"> OnlineDashboard</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Monitoring" asp-action="HistoricalData">HistoricalData</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Monitoring" asp-action="About">About</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <ul class="nav navbar-nav">
                            <li span class="nav-item">
                                <div class="nav-link font-color">
                                    Welcome @User.Identity!.Name
                                    <a class="bi-box-arrow-right text-decoration-none font-color" asp-controller="Account"
                                       asp-action="Logoff" data-toggle="tooltip" title="Log out"></a>
                                </div>
                            </li>
                        </ul> 
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

FYP/Views/Shared/Guest.cshtml
<style>
    .font-color {
        color: white;
    }
</style>

<div class="container border-bottom">
    <nav class="navbar navbar-expand-md">
        <div class="container-fluid">

            <img src="~/images/enviro-logo-white.png" height="20" width="90">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex justify-content-between w-100">
                    <div>
                        <ul class="nav navbar-nav">
                            <li>
                                <a class="nav-link font-color" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-color" asp-controller="Monitoring" asp-action="About">About</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <ul class="nav navbar-nav ml-auto">
                            <li>
                                <a class="text-end bi-box-arrow-in-right text-decoration-none font-color"
                                   asp-controller="Account" asp-action="Login" data-toggle="tooltip"
                                   title="Login">&nbsp;Login</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

FYP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/umd/popper.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <link href="~/lib/bootstrap/font/bootstrap-icons.min.css" rel="stylesheet" />

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/lib/chartjs/chart.min.js"></script>
    <script src="~/lib/chartjs/chartjs-plugin-datalabels.min.js"></script>
    <title>FYP</title>

    @RenderSection("MoreScripts", false)

</head>

<body>

    @if (User.Identity!.IsAuthenticated)
    {
        if (User.IsInRole("admin"))
        {
            <Partial name="Admin" />
        }
        else
        {
            <Partial name="Farmer" />
        }
    }
    else
    {
        <Partial name="Guest" />
    }

    <div class="container">
        @RenderBody()
    </div>
</body>
</html>